/**
 * GoBD Constants
 */

export const VALID_TAX_RATES = [0, 7, 19] as const;
export const DEFAULT_CURRENCY = 'EUR';
export const SUM_TOLERANCE = 0.01;

export const GOB_ERROR_CODES = {
  MISSING_INVOICE_NUMBER: 'MISSING_INVOICE_NUMBER',
  MISSING_ISSUE_DATE: 'MISSING_ISSUE_DATE',
  MISSING_NET_AMOUNT: 'MISSING_NET_AMOUNT',
  MISSING_TAX_AMOUNT: 'MISSING_TAX_AMOUNT',
  MISSING_GROSS_AMOUNT: 'MISSING_GROSS_AMOUNT',
  MISSING_CURRENCY: 'MISSING_CURRENCY',
  MISSING_SUPPLIER: 'MISSING_SUPPLIER',
  MISSING_CUSTOMER: 'MISSING_CUSTOMER',
  SUM_MISMATCH: 'SUM_MISMATCH',
  INVALID_TAX_RATE: 'INVALID_TAX_RATE',
  INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
  FUTURE_DATE: 'FUTURE_DATE',
  MISSING_LINE_ITEM_TAX_RATE: 'MISSING_LINE_ITEM_TAX_RATE',
  TAX_CALCULATION_ERROR: 'TAX_CALCULATION_ERROR',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  MISSING_LINE_ITEM_DESCRIPTION: 'MISSING_LINE_ITEM_DESCRIPTION',
  LINE_ITEM_SUM_MISMATCH: 'LINE_ITEM_SUM_MISMATCH',
} as const;

export const GOB_ERROR_MESSAGES: Record<string, string> = {
  [GOB_ERROR_CODES.MISSING_INVOICE_NUMBER]: 'Rechnungsnummer fehlt',
  [GOB_ERROR_CODES.MISSING_ISSUE_DATE]: 'Rechnungsdatum fehlt',
  [GOB_ERROR_CODES.MISSING_NET_AMOUNT]: 'Nettobetrag fehlt',
  [GOB_ERROR_CODES.MISSING_TAX_AMOUNT]: 'Steuerbetrag fehlt',
  [GOB_ERROR_CODES.MISSING_GROSS_AMOUNT]: 'Bruttobetrag fehlt',
  [GOB_ERROR_CODES.MISSING_CURRENCY]: 'Währung fehlt',
  [GOB_ERROR_CODES.MISSING_SUPPLIER]: 'Lieferant fehlt',
  [GOB_ERROR_CODES.MISSING_CUSTOMER]: 'Kunde fehlt',
  [GOB_ERROR_CODES.SUM_MISMATCH]: 'Summenabweichung',
  [GOB_ERROR_CODES.INVALID_TAX_RATE]: 'Ungültiger Steuersatz',
  [GOB_ERROR_CODES.INVALID_DATE_FORMAT]: 'Ungültiges Datumsformat',
  [GOB_ERROR_CODES.FUTURE_DATE]: 'Rechnungsdatum liegt in der Zukunft',
  [GOB_ERROR_CODES.MISSING_LINE_ITEM_TAX_RATE]: 'Steuersatz fehlt',
  [GOB_ERROR_CODES.TAX_CALCULATION_ERROR]: 'Steuerberechnung fehlerhaft',
  [GOB_ERROR_CODES.INVALID_CURRENCY]: 'Ungültige Währung',
  [GOB_ERROR_CODES.MISSING_LINE_ITEM_DESCRIPTION]: 'Beschreibung fehlt',
  [GOB_ERROR_CODES.LINE_ITEM_SUM_MISMATCH]: 'Positionssumme stimmt nicht',
};

export const GOB_WARNING_CODES = {
  MISSING_DUE_DATE: 'MISSING_DUE_DATE',
  NO_LINE_ITEMS: 'NO_LINE_ITEMS',
  UNCOMMON_CURRENCY: 'UNCOMMON_CURRENCY',
} as const;

export const GOB_WARNING_MESSAGES: Record<string, string> = {
  [GOB_WARNING_CODES.MISSING_DUE_DATE]: 'Fälligkeitsdatum fehlt',
  [GOB_WARNING_CODES.NO_LINE_ITEMS]: 'Keine Rechnungspositionen',
  [GOB_WARNING_CODES.UNCOMMON_CURRENCY]: 'Ungewöhnliche Währung',
};
